---
- name: Check for wordpress
  stat: path=/var/www/{{ item.name }}/www/wp-config.php
  register: has_wordpress
  with_items: '{{ sites_to_set_up }}'

- name: Set wp-content permissions
  command: chmod g+w /var/www/{{ item.item.name }}/www/wp-content
  with_items: '{{ has_wordpress.results }}'
  when: item.stat.exists == true

- name: Set wp-content/themes permissions
  command: chmod -R g+w /var/www/{{ item.item.name }}/www/wp-content/themes
  with_items: '{{ has_wordpress.results }}'
  when: item.stat.exists == true

- name: Set wp-content/plugins permissions
  command: chmod -R g+w /var/www/{{ item.item.name }}/www/wp-content/plugins
  with_items: '{{ has_wordpress.results }}'
  when: item.stat.exists == true

# - name: Set wp-content/cache permissions
#   command: chmod -R g+w /var/www/{{ item.name }}/www/wp-content/cache
#   with_items: '{{ sites_to_set_up }}'

- name: Set wp-content/uploads permissions
  command: chmod -R g+w /var/www/{{ item.item.name }}/www/wp-content/uploads
  with_items: '{{ has_wordpress.results }}'
  when: item.stat.exists == true
