---
- name: Install MySQL
  apt: name={{ item }} state=latest update_cache=true
  with_items:
    - python-mysqldb
    - mysql-server
    - mysql-client
    - libmysqlclient-dev

- name: Ensure MySQL service is up
  action: service name=mysql state=started

- name: Copy .my.cnf file with root password credentials
  template: src=templates/my.cnf dest=/root/.my.cnf owner=root mode=0600

- name: Update MySQL root password for all root accounts
  action: mysql_user name=root password={{ mysql_root_db_password  }} host_all=yes

- name: Ensure anonymous users are not in the database
  action: mysql_user name='' host={{ item }} state=absent
  with_items:
    - $ansible_hostname
    - localhost

- name: Create MySQL Database
  action: mysql_db name={{ item.name  }} state=present encoding=utf8mb4
  with_items: '{{ sites_to_set_up }}'

- name: Create MySQL User
  action: mysql_user name={{ item.name  }} priv={{ item.name  }}.*:ALL state=present password="{{ item.mysql_password }}"
  with_items: '{{ sites_to_set_up }}'
