---
- name: Install PHP
  apt: name={{ item }} state=latest update_cache=true
  with_items:
    - php-fpm
    - php-mysql
    - php7.0-opcache

- name: Set cgi.fix_pathinfo=0
  lineinfile:
    path: /etc/php/7.0/fpm/php.ini
    line: 'cgi.fix_pathinfo=0'

- name: Set pm.max_children
  lineinfile:
    path: /etc/php/7.0/fpm/pool.d/www.conf
    line: 'pm.max_children = 50'

- name: Set pm.start_servers
  lineinfile:
    path: /etc/php/7.0/fpm/pool.d/www.conf
    line: 'pm.start_servers = 25'

- name: Set pm.min_spare_servers
  lineinfile:
    path: /etc/php/7.0/fpm/pool.d/www.conf
    line: 'pm.min_spare_servers = 10'

- name: Set pm.max_spare_servers
  lineinfile:
    path: /etc/php/7.0/fpm/pool.d/www.conf
    line: 'pm.max_spare_servers = 25'

- name: Set pm.max_requests
  lineinfile:
    path: /etc/php/7.0/fpm/pool.d/www.conf
    line: 'pm.max_requests = 1000'

- name: restart php
  service: name=php7.0-fpm state=restarted enabled=yes
